2019-12-09 19:16:33,272 manager INFO 1.1.0
2019-12-09 19:16:33,272 manager INFO Copyright (C) 2003-2010
2019-12-09 19:16:33,272 manager INFO   Noriaki Ando
2019-12-09 19:16:33,272 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-09 19:16:33,272 manager INFO Manager starting.
2019-12-09 19:16:33,272 manager INFO Starting local logging.
2019-12-09 19:16:33,286 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-09 19:16:35,335 ManagerServant INFO Master manager not found
2019-12-09 19:16:35,335 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-09 19:16:35,413 LocalServiceAdmin INFO All the local services are enabled.
2019-12-09 19:16:35,538 ec_base INFO setRate(1000000.000000) done
2019-12-09 19:16:35,538 ec_base INFO setRate(1000.000000) done
2019-12-09 19:16:35,538 rtobject INFO 1 execution context was created.
2019-12-09 19:16:35,552 rtobject INFO Initial active configuration set is default-set.
2019-12-09 19:20:17,260 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-09 19:20:17,262 SdoServiceAdmin ERROR type  already exists.
2019-12-09 19:20:17,263 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-09 19:20:17,263 SdoServiceAdmin ERROR type e415c716-65d1-449d-a83b-b09913c6a8c8 already exists.
2019-12-09 19:25:05,196 sensor WARNING buffer empty
2019-12-09 19:25:05,253 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\CsvWrite\CsvWrite.py", line 172, in onExecute
    FSR_dic.setdefault(("FSR" + str(i)), line[i-1])
IndexError: list index out of range

2019-12-09 19:25:07,569 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2019-12-09 19:25:23,477 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2019-12-09 19:25:45,296 fin WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\PortBase.py", line 2262, in checkPorts
    if port._non_existent():
  File "C:\Python27\lib\site-packages\omniORB\CORBA.py", line 556, in _non_existent
    return self._obj.nonExistent()
TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

2019-12-09 19:25:45,296 fin WARNING Dead connection: b7295c40-1a6d-11ea-890e-40f02f22cc81
2019-12-09 19:25:46,328 fin WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\PortBase.py", line 836, in disconnect
    return p.notify_disconnect(connector_id)
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTM_IDL\RTC_idl.py", line 1207, in notify_disconnect
    return self._obj.invoke("notify_disconnect", _0_RTC.PortService._d_notify_disconnect, args)
TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

