2019-12-09 17:07:01,513 manager INFO 1.1.0
2019-12-09 17:07:01,513 manager INFO Copyright (C) 2003-2010
2019-12-09 17:07:01,513 manager INFO   Noriaki Ando
2019-12-09 17:07:01,513 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-09 17:07:01,513 manager INFO Manager starting.
2019-12-09 17:07:01,513 manager INFO Starting local logging.
2019-12-09 17:07:01,520 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-09 17:07:03,551 ManagerServant INFO Master manager not found
2019-12-09 17:07:03,553 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-09 17:07:03,555 LocalServiceAdmin INFO All the local services are enabled.
2019-12-09 17:07:03,569 manager INFO Component type conf file: Judge3.conf loaded.
2019-12-09 17:07:03,576 ec_base INFO setRate(1000000.000000) done
2019-12-09 17:07:03,576 ec_base INFO setRate(1000.000000) done
2019-12-09 17:07:03,578 rtobject INFO 1 execution context was created.
2019-12-09 17:07:03,582 rtobject INFO Initial active configuration set is default.
2019-12-09 17:07:05,940 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-09 17:07:05,940 SdoServiceAdmin ERROR type  already exists.
2019-12-09 17:07:05,940 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-09 17:07:05,940 SdoServiceAdmin ERROR type db6e90ce-5452-43c5-a926-16d89ceee16b already exists.
2019-12-09 17:07:08,082 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\Judge3\Judge3.py", line 177, in onExecute
    sensor_dic.setdefault(("sensor" + str(i)), data[i-1])
IndexError: list index out of range

