2019-12-09 15:41:18,250 manager INFO 1.1.0
2019-12-09 15:41:18,250 manager INFO Copyright (C) 2003-2010
2019-12-09 15:41:18,250 manager INFO   Noriaki Ando
2019-12-09 15:41:18,250 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-09 15:41:18,250 manager INFO Manager starting.
2019-12-09 15:41:18,250 manager INFO Starting local logging.
2019-12-09 15:41:18,250 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-09 15:41:20,318 ManagerServant INFO Master manager not found
2019-12-09 15:41:20,318 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-09 15:41:20,318 LocalServiceAdmin INFO All the local services are enabled.
2019-12-09 15:41:20,334 manager INFO Component type conf file: Change.conf loaded.
2019-12-09 15:41:20,334 ec_base INFO setRate(1000000.000000) done
2019-12-09 15:41:20,334 ec_base INFO setRate(1000.000000) done
2019-12-09 15:41:20,334 rtobject INFO 1 execution context was created.
2019-12-09 15:41:20,334 rtobject INFO Initial active configuration set is default-set.
2019-12-09 15:41:24,130 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-09 15:41:24,130 SdoServiceAdmin ERROR type  already exists.
2019-12-09 15:41:24,130 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-09 15:41:24,130 SdoServiceAdmin ERROR type 07e4b0d1-eb7a-42a4-9ca2-10e48134f634 already exists.
2019-12-09 15:41:31,964 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\Change\Change.py", line 130, in onExecute
    FSR_aa
UnboundLocalError: local variable 'FSR_aa' referenced before assignment

