2019-12-09 19:02:27,822 manager INFO 1.1.0
2019-12-09 19:02:27,822 manager INFO Copyright (C) 2003-2010
2019-12-09 19:02:27,822 manager INFO   Noriaki Ando
2019-12-09 19:02:27,822 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-09 19:02:27,822 manager INFO Manager starting.
2019-12-09 19:02:27,822 manager INFO Starting local logging.
2019-12-09 19:02:27,838 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-09 19:02:29,848 ManagerServant INFO Master manager not found
2019-12-09 19:02:29,851 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-09 19:02:29,852 LocalServiceAdmin INFO All the local services are enabled.
2019-12-09 19:02:29,862 manager INFO Component type conf file: Change.conf loaded.
2019-12-09 19:02:29,871 ec_base INFO setRate(1000000.000000) done
2019-12-09 19:02:29,871 ec_base INFO setRate(1000.000000) done
2019-12-09 19:02:29,872 rtobject INFO 1 execution context was created.
2019-12-09 19:02:29,878 rtobject INFO Initial active configuration set is default-set.
2019-12-09 19:02:32,783 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-09 19:02:32,783 SdoServiceAdmin ERROR type  already exists.
2019-12-09 19:02:32,799 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-09 19:02:32,799 SdoServiceAdmin ERROR type 7818104d-26c4-4222-a38b-65dc3efea5b5 already exists.
2019-12-09 19:02:44,039 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\Change\Change.py", line 144, in onExecute
    self._dataOut.write()
  File "C:\Python27\lib\site-packages\OpenRTM_aist\OutPort.py", line 181, in write
    ret = con.write(value)
  File "C:\Python27\lib\site-packages\OpenRTM_aist\OutPortPushConnector.py", line 240, in write
    cdr_data = cdrMarshal(any.to_any(data).typecode(), data, self._endian)
  File "C:\Python27\lib\site-packages\omniORB\__init__.py", line 229, in cdrMarshal
    return _omnipy.cdrMarshal(tc._d, data, endian)
BAD_PARAM: CORBA.BAD_PARAM(omniORB.BAD_PARAM_WrongPythonType, CORBA.COMPLETED_NO, ["Sequence item 0: expecting float, got <type 'str'>", "Struct 'TimedFloatSeq' member 'data'"])

2019-12-09 19:02:47,535 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
