2019-12-09 15:42:17,332 manager INFO 1.1.0
2019-12-09 15:42:17,332 manager INFO Copyright (C) 2003-2010
2019-12-09 15:42:17,332 manager INFO   Noriaki Ando
2019-12-09 15:42:17,332 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-09 15:42:17,332 manager INFO Manager starting.
2019-12-09 15:42:17,332 manager INFO Starting local logging.
2019-12-09 15:42:17,332 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-09 15:42:19,397 ManagerServant INFO Master manager not found
2019-12-09 15:42:19,400 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-09 15:42:19,411 LocalServiceAdmin INFO All the local services are enabled.
2019-12-09 15:42:19,421 manager INFO Component type conf file: Change.conf loaded.
2019-12-09 15:42:19,427 ec_base INFO setRate(1000000.000000) done
2019-12-09 15:42:19,427 ec_base INFO setRate(1000.000000) done
2019-12-09 15:42:19,427 rtobject INFO 1 execution context was created.
2019-12-09 15:42:19,430 rtobject INFO Initial active configuration set is default-set.
2019-12-09 15:42:41,278 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-09 15:42:41,278 SdoServiceAdmin ERROR type  already exists.
2019-12-09 15:42:41,279 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-09 15:42:41,279 SdoServiceAdmin ERROR type bda6ae42-491f-4d1d-b456-a8c22c73dd39 already exists.
2019-12-09 15:42:52,496 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\Change\Change.py", line 141, in onExecute
    FSR_aa = [ FSR_dic['FSR1'] , FSR_dic['FSR2'] ,FSR_dic['FSR3'] , FSR_dic['FSR4'] ,FSR_dic['FSR5'], FSR_dic['FSR6'] ,FSR_dic['FSR7'] , FSR_dic['FSR8'] ,FSR_dic['FSR9'], FSR_dic['FSR10'] ,FSR_dic['FSR11'] , FSR_dic['FSR12'] ,FSR_dic['FSR13'], FSR_dic['FSR14'] ,FSR_dic['FSR15'], FSR_dic['FSR16'] ]
KeyError: 'FSR16'

2019-12-09 15:42:57,569 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
