2019-12-07 19:47:33,736 manager INFO 1.1.0
2019-12-07 19:47:33,736 manager INFO Copyright (C) 2003-2010
2019-12-07 19:47:33,736 manager INFO   Noriaki Ando
2019-12-07 19:47:33,736 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-07 19:47:33,736 manager INFO Manager starting.
2019-12-07 19:47:33,736 manager INFO Starting local logging.
2019-12-07 19:47:33,743 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-07 19:47:35,766 ManagerServant INFO Master manager not found
2019-12-07 19:47:35,769 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-07 19:47:35,770 LocalServiceAdmin INFO All the local services are enabled.
2019-12-07 19:47:35,782 manager INFO Component type conf file: Change.conf loaded.
2019-12-07 19:47:35,789 ec_base INFO setRate(1000000.000000) done
2019-12-07 19:47:35,789 ec_base INFO setRate(1000.000000) done
2019-12-07 19:47:35,790 rtobject INFO 1 execution context was created.
2019-12-07 19:47:35,796 rtobject INFO Initial active configuration set is default-set.
2019-12-07 19:47:38,966 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-07 19:47:38,966 SdoServiceAdmin ERROR type  already exists.
2019-12-07 19:47:38,967 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-07 19:47:38,967 SdoServiceAdmin ERROR type 399528c1-3f8e-406f-a647-349af6e66d87 already exists.
2019-12-07 19:47:45,522 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\Change\Change.py", line 133, in onExecute
    answer = int(rawdata)
TypeError: int() argument must be a string or a number, not 'list'

