2019-12-09 19:10:15,819 manager INFO 1.1.0
2019-12-09 19:10:15,819 manager INFO Copyright (C) 2003-2010
2019-12-09 19:10:15,819 manager INFO   Noriaki Ando
2019-12-09 19:10:15,819 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-09 19:10:15,819 manager INFO Manager starting.
2019-12-09 19:10:15,819 manager INFO Starting local logging.
2019-12-09 19:10:15,834 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-09 19:10:17,868 ManagerServant INFO Master manager not found
2019-12-09 19:10:17,868 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-09 19:10:17,900 LocalServiceAdmin INFO All the local services are enabled.
2019-12-09 19:10:17,900 manager INFO Component type conf file: Change.conf loaded.
2019-12-09 19:10:17,915 ec_base INFO setRate(1000000.000000) done
2019-12-09 19:10:17,915 ec_base INFO setRate(1000.000000) done
2019-12-09 19:10:17,915 rtobject INFO 1 execution context was created.
2019-12-09 19:10:17,915 rtobject INFO Initial active configuration set is default-set.
2019-12-09 19:10:23,933 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-09 19:10:23,933 SdoServiceAdmin ERROR type  already exists.
2019-12-09 19:10:23,933 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-09 19:10:23,933 SdoServiceAdmin ERROR type ee398fca-f1cd-4cee-8fa1-09d545e15f2e already exists.
2019-12-09 19:10:41,341 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\Change\Change.py", line 144, in onExecute
    self._dataOut.write()
  File "C:\Python27\lib\site-packages\OpenRTM_aist\OutPort.py", line 181, in write
    ret = con.write(value)
  File "C:\Python27\lib\site-packages\OpenRTM_aist\OutPortPushConnector.py", line 240, in write
    cdr_data = cdrMarshal(any.to_any(data).typecode(), data, self._endian)
  File "C:\Python27\lib\site-packages\omniORB\__init__.py", line 229, in cdrMarshal
    return _omnipy.cdrMarshal(tc._d, data, endian)
BAD_PARAM: CORBA.BAD_PARAM(omniORB.BAD_PARAM_WrongPythonType, CORBA.COMPLETED_NO, ["Sequence item 0: expecting double, got <type 'str'>", "Struct 'TimedDoubleSeq' member 'data'"])

2019-12-09 19:10:44,013 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
