2019-12-07 19:18:59,242 manager INFO 1.1.0
2019-12-07 19:18:59,242 manager INFO Copyright (C) 2003-2010
2019-12-07 19:18:59,242 manager INFO   Noriaki Ando
2019-12-07 19:18:59,242 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-07 19:18:59,242 manager INFO Manager starting.
2019-12-07 19:18:59,242 manager INFO Starting local logging.
2019-12-07 19:18:59,242 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-07 19:19:01,305 ManagerServant INFO Master manager not found
2019-12-07 19:19:01,305 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-07 19:19:01,305 LocalServiceAdmin INFO All the local services are enabled.
2019-12-07 19:19:01,319 manager INFO Component type conf file: Change.conf loaded.
2019-12-07 19:19:01,319 ec_base INFO setRate(1000000.000000) done
2019-12-07 19:19:01,319 ec_base INFO setRate(1000.000000) done
2019-12-07 19:19:01,319 rtobject INFO 1 execution context was created.
2019-12-07 19:19:01,335 rtobject INFO Initial active configuration set is default-set.
2019-12-07 19:19:05,289 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-07 19:19:05,289 SdoServiceAdmin ERROR type  already exists.
2019-12-07 19:19:05,289 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-07 19:19:05,289 SdoServiceAdmin ERROR type 9b0bf012-43d2-4eda-9b78-b041d564680f already exists.
2019-12-07 19:19:11,197 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\Change\Change.py", line 131, in onExecute
    print(data[5])
IndexError: list index out of range

